#ifndef __DEFINITIONS_H__
#define __DEFINITIONS_H__

#define GROUND_GROUP -99
#define PLATFORM_GROUP -100
#define SHURIKEN_GROUP -101
#define PLAYER_GROUP -102


#define PLATFORM_BITMASK 0x01
#define PLAYER_BITMASK 0x02
#define SHURIKEN_BITMASK 0x03

#define DISPLAY_TIME_SPLASH_SCENE 2
#define TRANSITION_TIME 0.5
#define PIPE_SPAWN_FREQUENCY 0.005

#define PIPE_GAP 10
#define UPPER_SCREEN_PIPE_THRESHOLD 0.65
#define LOWER_SCREEN_PIPE_THRESHOLD 0.35

#define PIPE_MOVEMENT_SPEED 0.01

#define BIRD_FALLING_SPEED 0.0025
#define BIRD_FLYING_SPEED 0.00375
#define BIRD_FLY_DURATION 0.25

#define SCORE_FONT_SIZE 0.1

#endif // __DEFINITIONS_H__
